- id: doi:10.1038/s41592-021-01336-8
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41592-021-01336-8/MediaObjects/41592_2021_1336_Fig1_HTML.png?as=webp
  tags:
    - open science
    - benchmarking
    - single-cell
  repo: theislab/scib

- id: doi:10.1038/s41591-023-02327-2
  image: https://www.biorxiv.org/content/biorxiv/early/2022/03/11/2022.03.10.483747/F1.large.jpg?width=800&height=600&carousel=1
  tags:
    - lung
    - atlas
    - single-cell
  repo: LungCellAtlas/HLCA_reproducibility
